version: '3.8'

services:
  bedrockstatus:
    image: rdnsx/bedrockstatus
    environment:
      - SERVER=pietscraft.net # Change to your MC server domain!

# Optional add a preexisting proxy network
networks:
  default:
    external:
      name: npm_default