version: '3.8' 

services:
  php:
    image: rdnsx/bedrockstatus
    deploy:
      replicas: 3
      restart_policy:
        condition: unless-stopped

networks:
  default:
    external:
      name: npm_default
