version: '3.8'

services:
  bedrockstatus:
    image: rdnsx/bedrockstatus
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    environment:
      - SERVER=pietscraft.net # Change to your MC server domain!

# Optional: add a preexisting proxy network
networks:
  default:
    external:
      name: npm_default
